### PR TITLE
Customize report type

### PR DESCRIPTION
**Pull request by kafejo**
I've added option to specify report type in order to be able to fetch also subscription and other reports. 😎

### CODE REVIEW

**Comment by fedoco** [comment]
Thank you for participating! Unfortunately, your pull request isn't quite useable in its current form. It is not enough to add the report type parameter as you did because it is tightly coupled with the report subtype which is currently hardcoded to `Summary` in line 56 of the script. You would need to make the report subtype a parameter, too, and in addition take care that only valid combinations (see [Parameter Combinations](https://help.apple.com/itc/appsreporterguide/#/itcbd9ed14ac)) can be specified by the user.

But frankly I'm afraid that these changes will make the script unnecessarily complicated and I personally would hesitate to introduce two new parameters to the already quite convoluted command line. I therefore suggest to also add sensible default values for those new parameters so that they can be omitted in most of the usage cases of the script.

**Comment by fedoco** [comment]
Hello there, care to comment?

**Comment by kafejo** [comment]
Sorry, didn't mean to. I just needed it for internal usage and pushed it by mistake.

**Comment by fedoco** [comment]
All right.

**Pull request closed without merging**
